spring:
  application:
    name: "consumer-deivix"

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: AA-DEMO
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.deivix.dto"
        spring.json.use.type.headers: true

server:
  port: 8083